version: '3'

services:
  producer:
    build:
      context: ./
      dockerfile: ProducerDockerfile
    image: metrics-rest
    container_name: metrics-system
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dockerprod


